### ISSUE TITLE
Implement auto_ratios plugin

### ISSUE THREAD

**Issue by tatablack** [tatablack/beancount_tb_plugins#1]
When dealing with shared accounts and split expenses, on order to visualise both one's own share and the total some additional information is needed.

A plugin capable of identifying split transactions based on user-provided information (or less precise heuristics) could then add metadata to the transactions, namely the split ratio.

For this, we'd also need a series of `note` or `custom` directives, each one storing information about a time range and a split ratio that was in force during the range. The plugin would then, for each transaction, attach the correct ratio information to all relevant postings based on the date of the transaction itself.

## Tasks
- [x] identify eligible transactions
- [x] decide on the form of Ratio directives and add them
- [x] implement metadata adding
- [x] make it possible to identify split transactions attached to more than one account
- [ ] add unit tests
